# Generated by Django 2.2.10 on 2020-07-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='specification',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='grinder',
            name='specification',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='television',
            name='specification',
            field=models.TextField(max_length=500),
        ),
    ]
