# Generated by Django 2.2.10 on 2020-07-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='specification',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='specification',
            field=models.TextField(max_length=500),
        ),
    ]
